# Generated by Django 4.1.3 on 2022-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_profile_address_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
