# Generated by Django 4.1.3 on 2022-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_alter_article_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
