# Generated by Django 4.1.3 on 2022-11-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_savearticle"),
    ]

    operations = [
        migrations.RenameModel(old_name="SaveArticle", new_name="Save_article",),
    ]
